version: '3.1'
services:
  app:
    container_name: thinkme_clone
    image: thinkme_clone
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresqldb:5432/thinkme
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  #  mysql-standalone1:
  #    image: mysql:5.7
  #    environment:
  #      - MYSQL_ROOT_PASSWORD=root
  #      - MYSQL_DATABASE=test
  #      - MYSQL_USER=root
  #      - MYSQL_PASSWORD=root
  postgresqldb:
    image: postgres
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=thinkme